---
- name: Install qBittorrent-nox.
  ansible.builtin.package:
    name: qbittorrent-nox
    state: latest

- name: Create qBittorrent user.
  ansible.builtin.user:
    create_home: true
    name: qbtuser
    shell: /usr/sbin/nologin
